# Instrumented tests in Android

:insturmentedSource: ../app/src/androidTest/java/ch/amk/exercise4/mqtt

Android provide instrumented tests, which are test which are run
on a final device or emulator. This helps to test functionalities
in a real environment. Also it enables to create automated tests
for the GUI.

https://android.github.io/android-test/downloads/espresso-cheat-sheet-2.1.0.pdf[A helpful document is the espresso cheat sheet], which I recommend you to checkout.

## Add dependencies

Creating a new android project, all needed dependencies should be
already included. Also, there should be file *ExampleInstrumentedTest.java*.
Run this file to test, if Instrumented tests work

### Recomendation

Add mockito, hamcrest and awaitability to the test dependencies.

* http://hamcrest.org/[hamcrest] has great comparison functions
* https://site.mockito.org/[mockito] enables simple mocking
* https://github.com/awaitility/awaitility[awaitility] helps with asynchrone function tests,
  preventing the need for `Thread.sleep()` calls.

Following includes enables all of them:

.app/build.gradle
[source, gradle]
----
include::../app/build.gradle[tags=extBlock;dependenciesBlock;theGreatThree]
----
include::../app/build.gradle[tags=theGreatThreeDesc]

## Simple activity start

To get a feeling for instrumented tests, lets just start an activity.

.app/src/androidTest/../StartMainActivityInstrumentedTest.java
[source,java]
----
include::{insturmentedSource}/StartMainActivityInstrumentedTest.java[tags=!*]
----
include::{insturmentedSource}/StartMainActivityInstrumentedTest.java[tags=description]

By running this test, the emulator should start the MainActivity
and close it right away.

The `ActivityScenarioRule` also enables also following functionalities:

* `rule.getScenario().moveToState` change the current state of the Activity
* `rule.getScenario().recreate` recreate the Activity

[NOTE]
====
By using the Debug mode, it is really helpful to set an breakpoint
at the end of the test and start a specific activity without changing
the AndroidManifest.xml file.
====

## Clicking buttons

To be able to click a button, first it the button has to be found. Expresso provides the
`onView` function to find an object.

[source, java]
----
// find by R.id
Espresso.onView(R.id.element_id);

// using a matcher
Espresso.onView(ViewMatchers.withText("text"));
Espresso.onView(ViewMatchers.withContentDescription("text"));
----

Actions can be performed on the result with the function `perform()`.

[source, java]
----
// run click action
Espresso.onView(R.id.element_id).perform(ViewActions.click());
----

## Show GUI hierarchy

The Gui hierarchy can be printed if an objected is selected, which can not be found. The
hirarchy will show up in the log as exception.

[source, java]
----
Espresso.onView(ViewMatchers.withText("XYZ")).perform(ViewActions.click());
----

## Using Edit Text

If advanced actions are needed, the https://developer.android.com/training/testing/ui-automator[UIAnimator] is bringing those features. Including
to wait for an Object to appear, pressing buttons, ec.

### Add UIAnimator

.app/build.gradle
[source, gradle]
----
include::../app/build.gradle[tags=uiautomator;dependenciesBlock]
----

### Using the UIAnimator

The be able to use the `UIAnimator`, we first have to create an `UiDevice`, It is
recommended to make it a variable in the test:

[source, java]
----
include::{insturmentedSource}/ExampleExpressoInstrumentedTests.java[tags=uiDevice]
----

Next, like with the `Espresso`, we have to select our target components:

[source, java]
----
include::{insturmentedSource}/ExampleExpressoInstrumentedTests.java[tags=selectionExample]
----

### Enter into textfield

Same as with `espresso`

[source, java]
----
UiDevice device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());

// changing the text of the TextEdit with description *message_box*
device.findObject(new UiSelector().description("message_box")).setText("new text content");
----


