version: "2"
services:
  apigility:
    image: bigsisl/apigility-env
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'classicmodels'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
#      - my-db:/var/lib/mysql
